<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * PILOT CORPUS — Lagna, 1st, 7th and 10th Bhava.
 *
 * Interpretation fragments drawn from classical Parashari principles
 * (Brihat Parashara Hora Shastra and the standard commentary tradition).
 *
 * Each row is ONE assertion. The composer selects matching rows, resolves
 * contradictions by weight and polarity, then stitches them into flowing
 * paragraphs. Fragments are therefore written as sentence-level clauses
 * that read naturally when joined — not as standalone bullet points.
 *
 * polarity: -2 severe · -1 difficult · 0 neutral · +1 favourable · +2 strong
 * weight:   higher wins when two fragments contradict
 */
class InterpretationRuleSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('interpretation_rules')->where('locale', 'en')->delete();

        $rows = array_merge(
            $this->lagnaSigns(),
            $this->houseSigns(),
            $this->planetsInHouses(),
            $this->lordPlacements(),
            $this->dignityModifiers(),
            $this->digbalaModifiers(),
        );

        $now = now();
        foreach (array_chunk($rows, 200) as $chunk) {
            DB::table('interpretation_rules')->insert(array_map(
                fn ($r) => $r + ['locale' => 'en', 'created_at' => $now, 'updated_at' => $now],
                $chunk
            ));
        }

        $this->command->info('Seeded '.count($rows).' interpretation rules (pilot corpus).');
    }

    /** Lagna sign — the core temperament statement that opens a reading. */
    private function lagnaSigns(): array
    {
        $texts = [
            0 => 'a movable fire sign ruled by Mangal. This grants a forceful, pioneering temperament and considerable physical courage. You begin things readily and dislike being second. The same fire, however, turns inward when frustrated, producing impulsive decisions and anger that frequently lands on the wrong target',
            1 => 'a fixed earth sign ruled by Shukra. This gives patience, physical endurance and a strong attachment to comfort, beauty and material security. You move slowly but do not reverse once committed. The shadow of this fixity is obstinacy and a reluctance to abandon what has stopped serving you',
            2 => 'a dual air sign ruled by Budha. This produces a quick, verbal, adaptable intelligence with wide curiosity and easy social contact. You learn rapidly and explain well. The corresponding weakness is restlessness of mind and difficulty sustaining one direction long enough to finish it',
            3 => 'a movable water sign ruled by Chandra. This gives emotional sensitivity, retentive memory and strong protective instincts toward family. You read people accurately. The vulnerability is moodiness, a tendency to absorb the emotional atmosphere around you, and defensiveness when your security is touched',
            4 => 'a fixed fire sign ruled by Surya. This confers natural authority, dignity and an unwillingness to occupy a subordinate position. You lead by presence rather than argument. The difficulty is pride: criticism is felt as insult, and the need for recognition can override sound judgement',
            5 => 'a dual earth sign ruled by Budha. This produces analytical precision, discrimination and genuine capacity for detailed work. You notice what others miss. The cost is a critical inner voice that turns on yourself as readily as on others, and anxiety generated by your own standards',
            6 => 'a movable air sign ruled by Shukra. This gives diplomacy, aesthetic refinement and a real need for partnership and balance. You negotiate well. The weakness is indecision from seeing every side at once, and a tendency to concede your own position to preserve harmony',
            7 => 'a fixed water sign ruled by Mangal. This produces emotional intensity, penetrating insight and formidable resilience under pressure. You do not reveal yourself easily. The shadow is secretiveness, difficulty releasing injury, and a capacity for sustained resentment',
            8 => 'a dual fire sign ruled by Guru. This gives optimism, philosophical breadth and an instinct toward teaching, travel and ethical questions. You are direct to the point of bluntness. The weakness is overextension: promising more than time permits and losing interest once the idea is grasped',
            9 => 'a movable earth sign ruled by Shani. This confers discipline, realism and sustained ambition that tolerates long delay. You build slowly and permanently. The difficulty is pessimism, emotional reserve read by others as coldness, and a tendency to measure worth by achievement alone',
            10 => 'a fixed air sign ruled by Shani. This produces independent, unconventional thinking and genuine humanitarian concern. You think in systems rather than individuals. The corresponding weakness is emotional detachment and a stubbornness that hides beneath apparent open-mindedness',
            11 => 'a dual water sign ruled by Guru. This gives compassion, imagination and an intuitive grasp that bypasses reasoning. You absorb others readily. The vulnerability is poor boundaries, escapism under pressure, and difficulty maintaining practical structure',
        ];

        return array_map(fn ($sign) => [
            'condition_type' => 'lagna_sign',
            'condition_key' => (string) $sign,
            'section' => 'overview',
            'polarity' => 0,
            'weight' => 90,
            'text' => $texts[$sign],
            'conditions' => null,
        ], array_keys($texts));
    }

    /**
     * House × sign — how a bhava expresses through the sign on it.
     * Pilot covers houses 1, 7 and 10.
     */
    private function houseSigns(): array
    {
        $map = [
            1 => [
                0 => 'The body is lean and active, the bearing direct, and the approach to life confrontational rather than negotiated. Self-assertion comes easily; self-restraint does not',
                1 => 'The constitution is solid and the manner unhurried. You present as dependable and immovable, and you resist being rushed by anyone',
                2 => 'The build is slender and the manner animated. You define yourself through speech and ideas, and adapt your presentation to whoever is in front of you',
                3 => 'The face is round and the presence soft. You lead with feeling rather than argument, and your sense of self rests on emotional security',
                4 => 'The bearing is upright and noticeable. You occupy space naturally and expect to be treated with regard',
                5 => 'The build is neat and the manner precise. You present as competent and reserved, and judge yourself by standards no one else has set',
                6 => 'The features are pleasing and the manner accommodating. You define yourself substantially through relationship, and are uncomfortable in open conflict',
                7 => 'The gaze is direct and the presence guarded. You reveal little and observe much, and your self-understanding runs deeper than you disclose',
                8 => 'The frame is tall or expansive and the manner frank. You present as confident and are inclined to say what others are thinking',
                9 => 'The build is spare and the expression serious. You appear older than your years early in life and lighter later, and self-worth is tied to what you have built',
                10 => 'The bearing is distinctive and slightly apart. You present as friendly yet unreachable, and resist being categorised',
                11 => 'The eyes are expressive and the manner yielding. Your sense of self is fluid and takes colour from your surroundings',
            ],
            7 => [
                0 => 'The partner is assertive, energetic and independent, and the relationship carries a competitive charge. Conflict arrives early and openly rather than festering',
                1 => 'The partner is steady, sensual and materially grounded, and the union tends toward permanence once formed. Disagreement is rare but immovable when it comes',
                2 => 'The partner is communicative, youthful in manner and intellectually engaging. Two distinct phases or influences often mark the marital life',
                3 => 'The partner is nurturing, emotionally attuned and family-centred, and the home becomes the centre of the relationship. Moods govern the atmosphere more than events do',
                4 => 'The partner is dignified, proud and accustomed to being regarded. The relationship requires that both parties be seen, and suffers when one is eclipsed',
                5 => 'The partner is discerning, practical and helpful, though inclined to correct. Service is offered generously; criticism accompanies it',
                6 => 'The partner is refined, socially adept and genuinely committed to fairness. Harmony is prized, sometimes at the cost of saying what is true',
                7 => 'The partner is intense, private and emotionally deep. The bond is powerful and transformative, but jealousy and control must be consciously managed',
                8 => 'The partner is independent, philosophical and possibly of different background or distant origin. Freedom within the union is a condition of its survival',
                9 => 'The partner is mature, responsible and reserved, often older or weightier in manner. The marriage strengthens with time rather than beginning at its peak',
                10 => 'The partner is unconventional, independent-minded and resistant to ordinary expectation. The relationship works on its own terms or not at all',
                11 => 'The partner is compassionate, imaginative and emotionally receptive. Idealisation is a risk: seeing who you wish for rather than who is present',
            ],
            10 => [
                0 => 'The career demands initiative and tolerance of risk, favouring engineering, surgery, defence, athletics or any field rewarding decisive action. You work badly under close supervision',
                1 => 'The career favours finance, land, food, luxury goods, music or any field where value is built and held. Advancement is slow, steady and durable',
                2 => 'The career favours writing, teaching, trade, media, analysis and negotiation. Multiple occupations or parallel income streams are likely rather than one linear path',
                3 => 'The career favours care, hospitality, property, food, nursing or public service. Work must feel emotionally meaningful or it cannot be sustained',
                4 => 'The career favours authority, administration, government, medicine or public prominence. You require recognition and function poorly when anonymous',
                5 => 'The career favours analysis, health, accountancy, editing, research and systems. Competence is the reward sought, more than status',
                6 => 'The career favours law, diplomacy, design, counselling, the arts and any work conducted through partnership. You perform best in collaboration',
                7 => 'The career favours research, investigation, surgery, psychology, insurance or occult study. You are drawn to what is hidden and unafraid of crisis',
                8 => 'The career favours teaching, law, publishing, religion, higher education and advisory work. Ethical alignment matters more to you than remuneration',
                9 => 'The career favours administration, construction, mining, governance and long-horizon institutional work. Recognition arrives late but does not then depart',
                10 => 'The career favours technology, research, social reform, aviation and unconventional fields. Rigid hierarchy is intolerable to you',
                11 => 'The career favours healing, imagery, music, charity, spirituality or work near water. Commercial ruthlessness does not come naturally',
            ],
        ];

        $rows = [];
        foreach ($map as $house => $signs) {
            foreach ($signs as $sign => $text) {
                $rows[] = [
                    'condition_type' => 'house_sign',
                    'condition_key' => "{$house}:{$sign}",
                    'section' => "house_{$house}",
                    'polarity' => 0,
                    'weight' => 80,
                    'text' => $text,
                    'conditions' => null,
                ];
            }
        }

        return $rows;
    }

    /** Graha occupying houses 1, 7 and 10. */
    private function planetsInHouses(): array
    {
        $map = [
            1 => [
                'Sun' => [0, 'Surya in the Lagna gives authority in bearing and a strong sense of personal dignity, though it can harden into pride and a difficulty accepting correction. Constitution is generally robust; the father figure looms large in the formation of character'],
                'Moon' => [1, 'Chandra in the Lagna produces emotional responsiveness, an attractive manner and a mind that registers atmosphere quickly. Stability of mood is the lifelong work; the mother\'s influence on temperament is decisive'],
                'Mars' => [-1, 'Mangal in the Lagna gives physical vigour, competitive drive and a quick temper. It sharpens courage and shortens patience, and inclines toward injury, scars or surgical intervention. Restraint must be learned deliberately, as it is not native'],
                'Mercury' => [1, 'Budha in the Lagna gives quick comprehension, fluent speech and a youthful manner that persists well into later life. Nervous energy and overthinking are the accompanying costs'],
                'Jupiter' => [2, 'Guru in the Lagna is among the most protective placements available. It confers optimism, ethical instinct and a natural gravity that draws trust, and it restrains the harsher tendencies of the rising sign. Weight gain in later life is the common physical signature'],
                'Venus' => [2, 'Shukra in the Lagna gives physical attractiveness, refined taste and easy social warmth. Comfort is sought consistently, and there is reluctance to endure hardship that could be avoided'],
                'Saturn' => [-1, 'Shani in the Lagna imposes seriousness early. Childhood tends to carry responsibility or restriction, and the personality forms around endurance rather than ease. Its gift is discipline that outlasts everyone else\'s; its cost is a persistent undertone of insufficiency'],
                'Rahu' => [-1, 'Rahu in the Lagna produces an unusual, magnetic and somewhat unclassifiable presence. Ambition is strong and identity unsettled, with a pull toward the foreign or unconventional. Self-image tends to be either inflated or obscured, rarely accurate'],
                'Ketu' => [-1, 'Ketu in the Lagna gives detachment from ordinary self-definition and an inward, questioning cast of mind. There is often dissatisfaction with worldly identity and genuine aptitude for contemplative or investigative work, alongside a recurring sense of not quite belonging'],
            ],
            7 => [
                'Sun' => [-1, 'Surya in the 7th brings a proud and authoritative partner, and introduces a contest of standing within the marriage. Ego must be negotiated consciously, or the relationship becomes a competition for primacy'],
                'Moon' => [1, 'Chandra in the 7th gives a caring, emotionally attuned partner and a genuine need for companionship. The marital atmosphere fluctuates with mood, and solitude is poorly tolerated'],
                'Mars' => [-2, 'Mangal in the 7th is the classical Kuja Dosha placement. It brings a forceful partner and friction over dominance, with arguments igniting quickly. Delaying marriage and choosing a partner of comparable temperament materially reduces the difficulty'],
                'Mercury' => [1, 'Budha in the 7th gives an intelligent, articulate and youthful partner. The relationship is sustained by conversation, and the union may involve business dealings alongside affection'],
                'Jupiter' => [2, 'Guru in the 7th brings a principled, generous and often well-educated partner, and confers real protection on the marriage. It is among the strongest indications of a fortunate and stabilising union'],
                'Venus' => [1, 'Shukra in the 7th brings an attractive, affectionate partner and strong marital happiness, provided the pursuit of pleasure does not outrun commitment'],
                'Saturn' => [-1, 'Shani in the 7th delays marriage and brings a serious, dutiful, frequently older partner. The early years are demanding, but this placement rewards persistence: the bond becomes one of the most durable in the chart'],
                'Rahu' => [-1, 'Rahu in the 7th indicates an unconventional union, often crossing lines of culture, caste, religion or distance. Expectation and reality diverge sharply, and disillusionment follows if the partner was idealised'],
                'Ketu' => [-1, 'Ketu in the 7th produces emotional detachment within partnership and a recurring sense of separateness even in closeness. There may be indifference to marriage itself, or a bond that feels karmic and unchosen'],
            ],
            10 => [
                'Sun' => [2, 'Surya in the 10th is a powerful placement for career. It confers authority, visibility and advancement through position, with genuine capacity for leadership and government or institutional work'],
                'Moon' => [1, 'Chandra in the 10th gives a public-facing career and fluctuating professional fortune. Work involving people, care or the general public suits you; a purely technical role will not hold your interest'],
                'Mars' => [2, 'Mangal in the 10th grants drive, executive capability and the willingness to take professional risk. It suits engineering, surgery, defence and any competitive field, though it makes you a difficult subordinate'],
                'Mercury' => [1, 'Budha in the 10th favours communication, commerce, analysis and writing in the professional sphere. Several occupations across a lifetime are more likely than one'],
                'Jupiter' => [2, 'Guru in the 10th brings an honourable and respected career, with aptitude for teaching, law, advisory or ethical work. Reputation becomes a durable professional asset'],
                'Venus' => [1, 'Shukra in the 10th favours a career in the arts, design, luxury, entertainment or diplomacy. The working environment must be pleasant, or performance falls away'],
                'Saturn' => [1, 'Shani in the 10th produces slow, laborious professional ascent followed by unusually durable standing. Early recognition is withheld; what is eventually built does not collapse. Public service, administration and long-horizon institutions suit you'],
                'Rahu' => [1, 'Rahu in the 10th generates strong ambition and can lift you far above your origins, particularly in foreign, technological or unconventional fields. The rise may be rapid and the methods questioned'],
                'Ketu' => [-1, 'Ketu in the 10th brings ambivalence toward worldly success. Achievement arrives but satisfies less than expected, and there is a pull toward work of meaning rather than status'],
            ],
        ];

        $rows = [];
        foreach ($map as $house => $planets) {
            foreach ($planets as $planet => [$polarity, $text]) {
                $rows[] = [
                    'condition_type' => 'planet_house',
                    'condition_key' => "{$planet}:{$house}",
                    'section' => "house_{$house}",
                    'polarity' => $polarity,
                    'weight' => 70,
                    'text' => $text,
                    'conditions' => null,
                ];
            }
        }

        return $rows;
    }

    /**
     * House lord placement — the strongest predictive layer in Parashari
     * astrology, and what separates a real reading from a generic one.
     */
    private function lordPlacements(): array
    {
        $lagnesh = [
            1 => [2, 'placed in the Lagna itself, which strengthens the constitution and makes self-direction the governing theme of life. You are the principal author of your own circumstances, for better and worse'],
            2 => [1, 'placed in the 2nd, tying your identity to wealth, family and speech. Earning capacity is good, and how you speak substantially determines how you are received'],
            3 => [1, 'placed in the 3rd, giving self-made courage and advancement through personal effort rather than inheritance. Siblings and short journeys figure prominently'],
            4 => [1, 'placed in the 4th, anchoring identity in home, mother and inner peace. Property is acquired, and domestic disturbance affects you more than most'],
            5 => [2, 'placed in the 5th, favouring intelligence, children and creative expression. Learning comes readily and past merit supports the present life'],
            6 => [-1, 'placed in the 6th, which turns the self toward conflict, service and health. You overcome enemies but expend yourself doing so, and must guard against chronic depletion'],
            7 => [0, 'placed in the 7th, making partnership central to self-definition. You discover yourself through others, which is a strength in collaboration and a liability in isolation'],
            8 => [-2, 'placed in the 8th, one of the more difficult placements for the Lagna lord. It brings health vulnerability, sudden reversals and a life marked by transformation. It also grants genuine research capacity and interest in what lies beneath the surface. Haste and risk-taking are the specific dangers to manage'],
            9 => [2, 'placed in the 9th, among the most fortunate placements available. Fortune supports you, the father or a teacher figure aids materially, and ethical clarity guides decisions'],
            10 => [2, 'placed in the 10th, directing the self powerfully toward career and public standing. Professional identity and personal identity are nearly the same thing for you'],
            11 => [2, 'placed in the 11th, favouring gains, networks and the fulfilment of ambition. Friends and elder siblings assist, and income grows steadily'],
            12 => [-1, 'placed in the 12th, inclining toward foreign residence, solitude and inner life. Expenditure runs high and worldly ambition is muted, but spiritual capacity is genuine'],
        ];

        $seventhLord = [
            1 => [1, 'placed in the Lagna, bringing the partner close into your own sphere. You may marry someone already known to you, and the relationship shapes your identity directly'],
            2 => [1, 'placed in the 2nd, linking marriage to family wealth and domestic stability. The union tends to improve financial standing'],
            3 => [0, 'placed in the 3rd, suggesting a partner encountered through siblings, neighbours or short travel, and a relationship requiring continual communication'],
            4 => [1, 'placed in the 4th, bringing the marriage into the home and often the partner into the family property. Domestic life and marital life are inseparable'],
            5 => [1, 'placed in the 5th, indicating a love match and a relationship in which children figure centrally'],
            6 => [-2, 'placed in the 6th, which introduces friction, litigation or health concerns into the marriage. Disputes are likely and require deliberate management rather than avoidance'],
            7 => [2, 'placed in the 7th itself, strengthening the marriage considerably. The partner is well-matched and the union stable'],
            8 => [-2, 'placed in the 8th, bringing obstacles, secrecy or sudden disturbance to married life. Longevity concerns for the partner may arise. This placement demands transparency; concealment magnifies every difficulty it brings'],
            9 => [2, 'placed in the 9th, indicating a fortunate marriage that expands your world. The partner may come from a distance or a different background and raises your circumstances'],
            10 => [1, 'placed in the 10th, connecting marriage to career and public life. The partner assists professionally, or you meet through work'],
            11 => [1, 'placed in the 11th, bringing gain through marriage and a partner who widens your social network'],
            12 => [-1, 'placed in the 12th, indicating separation, foreign residence or extended periods apart. Distance is a recurring feature of the relationship'],
        ];

        $tenthLord = [
            1 => [2, 'placed in the Lagna, fusing career with personal identity. You build your profession on your own name and presence'],
            2 => [1, 'placed in the 2nd, directing career toward wealth accumulation, family enterprise or work involving speech and finance'],
            3 => [1, 'placed in the 3rd, favouring careers built on communication, initiative and self-marketing. Progress comes from persistent personal effort'],
            4 => [1, 'placed in the 4th, suiting work from home, in property, education or vehicles. The mother or homeland figures in professional life'],
            5 => [2, 'placed in the 5th, favouring creative, speculative or education-related careers. Intelligence is your professional instrument'],
            6 => [0, 'placed in the 6th, indicating a career in service, health, law or dispute resolution. Competition is constant but you are equipped for it'],
            7 => [1, 'placed in the 7th, favouring business, partnership and public dealing. You work better with someone than alone'],
            8 => [-1, 'placed in the 8th, bringing professional instability and sudden change of course, alongside genuine aptitude for research, insurance or investigative work'],
            9 => [2, 'placed in the 9th, a strong Raja Yoga combination. Career is supported by fortune, teachers and ethical standing, and rises substantially'],
            10 => [2, 'placed in the 10th itself, giving a powerful and self-sustaining professional life with real authority'],
            11 => [2, 'placed in the 11th, converting career directly into income and gain. Professional networks are your principal asset'],
            12 => [-1, 'placed in the 12th, indicating career abroad, in institutions, or in work removed from public visibility. Recognition is limited but the work may matter more than the recognition'],
        ];

        $rows = [];
        foreach ([1 => $lagnesh, 7 => $seventhLord, 10 => $tenthLord] as $ownHouse => $placements) {
            foreach ($placements as $inHouse => [$polarity, $text]) {
                $rows[] = [
                    'condition_type' => 'lord_in_house',
                    'condition_key' => "{$ownHouse}:{$inHouse}",
                    'section' => "house_{$ownHouse}",
                    'polarity' => $polarity,
                    'weight' => 85,
                    'text' => $text,
                    'conditions' => null,
                ];
            }
        }

        return $rows;
    }

    /** Dignity modifiers, applied to whichever planet carries them. */
    private function dignityModifiers(): array
    {
        $map = [
            'exalted' => [2, 90, 'is exalted here, giving its significations unusual strength and reliability'],
            'moolatrikona' => [2, 85, 'occupies its moolatrikona, where it functions with near-full power'],
            'own' => [1, 80, 'rests in its own sign, so it acts freely and without obstruction'],
            'friendly' => [1, 60, 'sits in a friendly sign and is comfortably placed'],
            'neutral' => [0, 40, 'is neutrally placed and acts according to the rest of the chart'],
            'enemy' => [-1, 60, 'sits in an inimical sign, which constrains it and forces its results through resistance'],
            'debilitated' => [-2, 90, 'is debilitated here, weakening its significations considerably. What it governs must be earned rather than received'],
        ];

        $rows = [];
        foreach ($map as $dignity => [$polarity, $weight, $text]) {
            $rows[] = [
                'condition_type' => 'dignity',
                'condition_key' => $dignity,
                'section' => 'modifier',
                'polarity' => $polarity,
                'weight' => $weight,
                'text' => $text,
                'conditions' => null,
            ];
        }

        $rows[] = [
            'condition_type' => 'condition',
            'condition_key' => 'retrograde',
            'section' => 'modifier',
            'polarity' => 0,
            'weight' => 50,
            'text' => 'is retrograde, so its results arrive late, repeat themselves, or turn inward before they express outwardly',
            'conditions' => null,
        ];

        $rows[] = [
            'condition_type' => 'condition',
            'condition_key' => 'combust',
            'section' => 'modifier',
            'polarity' => -1,
            'weight' => 65,
            'text' => 'is combust, burnt by proximity to the Sun, which suppresses its outward expression even where it is otherwise well placed',
            'conditions' => null,
        ];

        return $rows;
    }

    /** Directional strength commentary. */
    private function digbalaModifiers(): array
    {
        return [
            [
                'condition_type' => 'digbala',
                'condition_key' => 'full',
                'section' => 'modifier',
                'polarity' => 2,
                'weight' => 70,
                'text' => 'holds full directional strength (Digbala) in this position, which amplifies everything it signifies',
                'conditions' => null,
            ],
            [
                'condition_type' => 'digbala',
                'condition_key' => 'strong',
                'section' => 'modifier',
                'polarity' => 1,
                'weight' => 55,
                'text' => 'is directionally well placed, lending steadiness to its results',
                'conditions' => null,
            ],
            [
                'condition_type' => 'digbala',
                'condition_key' => 'weak',
                'section' => 'modifier',
                'polarity' => -1,
                'weight' => 55,
                'text' => 'lacks directional strength here, so its results require deliberate effort to materialise',
                'conditions' => null,
            ],
            [
                'condition_type' => 'digbala',
                'condition_key' => 'powerless',
                'section' => 'modifier',
                'polarity' => -2,
                'weight' => 70,
                'text' => 'is directionally powerless in this house, which markedly undercuts its capacity to deliver',
                'conditions' => null,
            ],
        ];
    }
}
