<?php

namespace Database\Seeders\Rules;

/**
 * Core rules: the 12 Lagna temperament statements plus the modifier
 * vocabulary (dignity, retrogression, combustion, directional strength)
 * that attaches to any graha anywhere in the chart.
 */
class CoreRules
{
    public static function all(): array
    {
        return array_merge(
            self::lagnaSigns(),
            self::dignityModifiers(),
            self::digbalaModifiers(),
        );
    }

    public static function lagnaSigns(): array
    {
        $texts = [
            0 => 'a movable fire sign ruled by Mangal. This grants a forceful, pioneering temperament and considerable physical courage. You begin things readily and dislike being second. The same fire, however, turns inward when frustrated, producing impulsive decisions and anger that frequently lands on the wrong target',
            1 => 'a fixed earth sign ruled by Shukra. This gives patience, physical endurance and a strong attachment to comfort, beauty and material security. You move slowly but do not reverse once committed. The shadow of this fixity is obstinacy and a reluctance to abandon what has stopped serving you',
            2 => 'a dual air sign ruled by Budha. This produces a quick, verbal, adaptable intelligence with wide curiosity and easy social contact. You learn rapidly and explain well. The corresponding weakness is restlessness of mind and difficulty sustaining one direction long enough to finish it',
            3 => 'a movable water sign ruled by Chandra. This gives emotional sensitivity, retentive memory and strong protective instincts toward family. You read people accurately. The vulnerability is moodiness, a tendency to absorb the emotional atmosphere around you, and defensiveness when your security is touched',
            4 => 'a fixed fire sign ruled by Surya. This confers natural authority, dignity and an unwillingness to occupy a subordinate position. You lead by presence rather than argument. The difficulty is pride: criticism is felt as insult, and the need for recognition can override sound judgement',
            5 => 'a dual earth sign ruled by Budha. This produces analytical precision, discrimination and genuine capacity for detailed work. You notice what others miss. The cost is a critical inner voice that turns on yourself as readily as on others, and anxiety generated by your own standards',
            6 => 'a movable air sign ruled by Shukra. This gives diplomacy, aesthetic refinement and a real need for partnership and balance. You negotiate well. The weakness is indecision from seeing every side at once, and a tendency to concede your own position to preserve harmony',
            7 => 'a fixed water sign ruled by Mangal. This produces emotional intensity, penetrating insight and formidable resilience under pressure. You do not reveal yourself easily. The shadow is secretiveness, difficulty releasing injury, and a capacity for sustained resentment',
            8 => 'a dual fire sign ruled by Guru. This gives optimism, philosophical breadth and an instinct toward teaching, travel and ethical questions. You are direct to the point of bluntness. The weakness is overextension: promising more than time permits and losing interest once the idea is grasped',
            9 => 'a movable earth sign ruled by Shani. This confers discipline, realism and sustained ambition that tolerates long delay. You build slowly and permanently. The difficulty is pessimism, emotional reserve read by others as coldness, and a tendency to measure worth by achievement alone',
            10 => 'a fixed air sign ruled by Shani. This produces independent, unconventional thinking and genuine humanitarian concern. You think in systems rather than individuals. The corresponding weakness is emotional detachment and a stubbornness that hides beneath apparent open-mindedness',
            11 => 'a dual water sign ruled by Guru. This gives compassion, imagination and an intuitive grasp that bypasses reasoning. You absorb others readily. The vulnerability is poor boundaries, escapism under pressure, and difficulty maintaining practical structure',
        ];

        return array_map(fn ($sign) => [
            'condition_type' => 'lagna_sign',
            'condition_key' => (string) $sign,
            'section' => 'overview',
            'polarity' => 0,
            'weight' => 90,
            'text' => $texts[$sign],
            'conditions' => null,
        ], array_keys($texts));
    }

    public static function dignityModifiers(): array
    {
        $map = [
            'exalted' => [2, 90, 'is exalted here, giving its significations unusual strength and reliability'],
            'moolatrikona' => [2, 85, 'occupies its moolatrikona, where it functions with near-full power'],
            'own' => [1, 80, 'rests in its own sign, so it acts freely and without obstruction'],
            'friendly' => [1, 60, 'sits in a friendly sign and is comfortably placed'],
            'neutral' => [0, 40, 'is neutrally placed and acts according to the rest of the chart'],
            'enemy' => [-1, 60, 'sits in an inimical sign, which constrains it and forces its results through resistance'],
            'debilitated' => [-2, 90, 'is debilitated here, weakening its significations considerably. What it governs must be earned rather than received'],
        ];

        $rows = [];
        foreach ($map as $dignity => [$polarity, $weight, $text]) {
            $rows[] = [
                'condition_type' => 'dignity',
                'condition_key' => $dignity,
                'section' => 'modifier',
                'polarity' => $polarity,
                'weight' => $weight,
                'text' => $text,
                'conditions' => null,
            ];
        }

        $rows[] = [
            'condition_type' => 'condition',
            'condition_key' => 'retrograde',
            'section' => 'modifier',
            'polarity' => 0,
            'weight' => 50,
            'text' => 'is retrograde, so its results arrive late, repeat themselves, or turn inward before they express outwardly',
            'conditions' => null,
        ];

        $rows[] = [
            'condition_type' => 'condition',
            'condition_key' => 'combust',
            'section' => 'modifier',
            'polarity' => -1,
            'weight' => 65,
            'text' => 'is combust, burnt by proximity to the Sun, which suppresses its outward expression even where it is otherwise well placed',
            'conditions' => null,
        ];

        return $rows;
    }

    public static function digbalaModifiers(): array
    {
        return [
            [
                'condition_type' => 'digbala',
                'condition_key' => 'full',
                'section' => 'modifier',
                'polarity' => 2,
                'weight' => 70,
                'text' => 'holds full directional strength (Digbala) in this position, which amplifies everything it signifies',
                'conditions' => null,
            ],
            [
                'condition_type' => 'digbala',
                'condition_key' => 'strong',
                'section' => 'modifier',
                'polarity' => 1,
                'weight' => 55,
                'text' => 'is directionally well placed, lending steadiness to its results',
                'conditions' => null,
            ],
            [
                'condition_type' => 'digbala',
                'condition_key' => 'weak',
                'section' => 'modifier',
                'polarity' => -1,
                'weight' => 55,
                'text' => 'lacks directional strength here, so its results require deliberate effort to materialise',
                'conditions' => null,
            ],
            [
                'condition_type' => 'digbala',
                'condition_key' => 'powerless',
                'section' => 'modifier',
                'polarity' => -2,
                'weight' => 70,
                'text' => 'is directionally powerless in this house, which markedly undercuts its capacity to deliver',
                'conditions' => null,
            ],
        ];
    }
}
